### ISSUE TITLE
Please provide https update site

### ISSUE THREAD

**Issue by iloveeclipse** [uvoigt/zipeditor#1]
See https://mikael.barbero.tech/blog/post/enforce-https-eclipse-marketplace/
Eclipse Foundation wants to force all providers to use https to avoid man in the middle attacs.

However, the update site for zipeditor isn't available over https: https://zipeditor.sourceforge.net/update/site.xml doesn't work, but http://zipeditor.sourceforge.net/update/site.xml does.

**Comment by iloveeclipse** [comment]
Note: sourceforge allows to convert sites to https: https://sourceforge.net/p/forge/documentation/Convert%20your%20website%20to%20HTTPS/

**Comment by uvoigt** [comment]
Modified the update site to https://zipeditor.sourceforge.net/update/site.xml.
Thanks for notifying me!

**Comment by iloveeclipse** [comment]
Thanks Uwe.
